# Basic Information 
title: Yang Bai
position: Senior Research Scientist
affiliation: Tencent
affiliation_link: https://www.tencent.com/
email: mavisbai (at) tencent.com
email2: baiyang0522 (at) gmail.com

# Search Engine Optimization (SEO)
keywords: yang bai, yangbai, baiyang, bai yang, mavisbai
description: Yang Bai is a senior research scientist at Tencent. Her research lies in non-convex optimization, LLM, VLM and robust machine learning.

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=wBH_Q1gAAAAJ&hl=zh-CN
github_link: https://github.com/bymavis/
linkedin: https://www.linkedin.com/in/yangbai/

# Images 
avatar: ./assets/img/myprofile.png

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
